# LIST 2 DIMENSI

In [7]:
###############################################################################################################################
#Nama: Anak Agung Istri Agung Yulia Prameswari
#NIM : 2208541007
#Kelas: A 
#Tugas V
###############################################################################################################################

In [3]:
#List 2 dimensi adalah menempatkan sebuah list di dalam list.
#Penggambarannya seperti sebuah matrik

#contoh list 2 dimensi
matrik = [
    [7,22,24,26],
    [26,24,22,7],
    [24,22,26,7]
]
print("semua matriks yaitu: ", matrik)
#pada list 2 dimensi menggunakan "[[ ]]"
#matriks baris pertama akan muncul jika kita memanggil matrik 0 dan 
#matriks baris terakhir akan muncul jika kita memanggil matrik 2 pada matriks ini 
print("matriks baris pertama adalah: ", matrik[0])
print("matriks baris terakhir adalah: ", matrik[2])

semua matriks yaitu:  [[7, 22, 24, 26], [26, 24, 22, 7], [24, 22, 26, 7]]
matriks baris pertama adalah:  [7, 22, 24, 26]
matriks baris terakhir adalah:  [24, 22, 26, 7]


In [6]:
for baris in matrik: 
    print(baris)
    for kolom in baris:
        print(kolom)
#matriks akan dibuat baris terlebih dahulu
#kemudian dari baris akan di bentuk menjadi kolom 

[7, 22, 24, 26]
7
22
24
26
[26, 24, 22, 7]
26
24
22
7
[24, 22, 26, 7]
24
22
26
7


# Tuples 

In [64]:
#Tuples mirip dengan list, akan tetapi tuples tidak dapat dirubah isinya
#data yang kita buat menggunakan tuples sama sekali tidak bisa dirubah isinya
#jadi sebaiknya jika datanya masi ingin dirubah lebih baik menggunakan list saja. 

ukuran_sepatu = (37,38,39,40,41)
print(ukuran_sepatu[0])
print('\n')

print(ukuran_sepatu[2:5])
#data dimulai dari 0 

37


(39, 40, 41)


In [33]:
#mengurutkan data menjadi kolom 
for isi in ukuran_sepatu [0:5]:
    print (isi)

#kita coba tambahkan 42 pada 'ukuran_sepatu'    
ukuran_sepatu.append(42)
#setelah di panggil ternyata tidak bisa, hasil yang dikeluarkan error

#kita coba untuk hapus 38 dari 'ukuran_sepatu'
ukuran_sepatu.remove(38)
#setelah di panggil hasilnya error
#hal ini terjadi karena pada tuples tidak bisa menambah, mengurangi maupun mengubah apapun 

37
38
39
40
41


AttributeError: 'tuple' object has no attribute 'append'

# Dictionaries

In [13]:
#Dictionaries digunakan jika data nya terkait satu sama lain
#Misalnya data seseorang yang terdiri dari umur, nama, tanggal lahir 
#merupakan satu kesatuan data yang bersumber dari orang tersebut

data_orang = {
    "nama" : "gung gek swari",
    "umur" : 17, 
    "perempuan" : True 
}
print("nama: ", data_orang ['nama'])
print("umur: ", data_orang ['umur'])
print("apakah perempuan? ", data_orang ['perempuan'])


nama:  gung gek swari
umur:  17
apakah perempuan?  True


In [17]:
print(data_orang.get("tanggal_lahir"))
#tanggal lahir  ini akan menampilkan 'none' karena tidak ada pada 'data_orang'
#jika ingin menambahkan data maka harus memasukan nama data dan datanya 

print(data_orang.get("tanggal_lahir", "19 07 2005"))
#ini akan muncul jika kita mengisi nama data dan datanya langsung
#karena jika hanya memanggil nama data tanpa datanya lansung maka hasilnya akan 'none'
#data tersebut bersifat sementara 

print(data_orang("tanggal_lahir"))
#saat kita memangil data ini lagi maka akan error karena tanggal lahir ini tidak masuk ke dalam data 

None
19 07 2005


TypeError: 'dict' object is not callable

In [18]:
print(data_orang)
#walaupun tadi kita ada menambahkan data "tanggal lahir" tetapi dia tidak akan muncul jika kita memanggil "data_orang"
#karena data.get hanya akan ada saat data itu dijabarkan saja, seperti di atas

{'nama': 'gung gek swari', 'umur': 17, 'perempuan': True}


# Fungsi dalam Python

In [38]:
#Fungsi dalam Python dibentuk untuk menghidari pengulangan pembuatan program secara manual
#dimana fungsi tersebut memiliki pengulangan yang tinggi dalam program yang kita buat

#jebarkan pengoperasian waktu_sampai
def waktu_sampai (jarak,kecepatan):
    waktu = jarak/kecepatan 
    return waktu 

y = waktu_sampai (50,80)
#variabel a berfungsi untuk memanggil waktu_sampai 
#jaraknya adalah 50 km dan kecepatannya adalah 80 km/jam
print ("jika jarak tempuh sebuah sepeda motor adalah 50 km dengan kecepatan motor 80 km/jam")
print ("maka sepeda motor akan sampai pada tempat tujuan setelah" , y , "jam")

jika jarak tempuh sebuah sepeda motor adalah 50 km dengan kecepatan motor 80 km/jam
maka sepeda motor akan sampai pada tempat tujuan setelah 0.625 jam


# Numpy

In [28]:
#Numpy merupakan salah satu Library dalam Python yang memiliki keunggulan
#dalam perhitungan menggunakan vektor dam matrik dalam berbagai dimensi
#Hal pertama yang perlu dilakukan adalah memanggil Library Numpy

import numpy as np 

## Perintah Dasar pada Numpy

In [29]:
a = np.array([7,22,24,26])
print("data a yaitu: ")
print(a)
print('\n')
#numpy akan menjadikan array sebagai matriks 
#data dalam '[ ]' akan menjadi baris 

b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("data b yaitu: ")
print(b)
print('\n')
#numpy akan menjadikan array sebagai matriks 
#data dalam '[[ ]]' akan menjadi kolom

c = np.array([[[1,2,3], [3,4,5]],
             [[6,7,8], [9,10,11]],
             [[12,13,14], [15,16,17]]])
print("data c yaitu: ")
print(c)
print('\n')
#numpy akan menjadikan array sebagai matriks 
#data dalam '[[[ ]]]' akan menjadi kolom dan setiap '[[ ]]' akan berisi spasi

print("banyak kolom pada data c dan")
c.ndim
#ndim adalah untuk menampilkan banyaknya baris dalam suatu data 
print("banyak baris pada data b adalah")
b.shape
#shape adalah untuk menampilkan banyaknya kolom dalam suatu data 
#jika kita memanggil dengan cara ini maka hasil yang keluar akan menjadi satu 
#karena out dalam satu comment hanya bisa satu out
#jadi hasil yang akan ditampilkan adalah (3,3)
#kolom pada data c adalah 3 dan baris pada data b adalah 3

data a yaitu: 
[ 7 22 24 26]


data b yaitu: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


data c yaitu: 
[[[ 1  2  3]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


banyak kolom pada data c dan
banyak baris pada data b adalah


(3, 3)

## Memanggil Anggota, Kolom dan Baris dengan Numpy

In [30]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print('\n')
#data tersebut akan terlihat pada hasil menjadi kolom 

#b[baris data, kolom data]
#semuanya dihitung mulai dari 0 
b[0,2]
#berarti memanggil baris pertama kolom ke tiga 
#pada data terbetu angka yang menempati baris pertama kolom ke tiga adalah angka 3 

[[1 2 3]
 [4 5 6]
 [7 8 9]]




3

In [31]:
b[0,:]
#memanggil semua baris pertama 

array([1, 2, 3])

In [32]:
b[0,0] = 100
#ini akan mengubah data b baris pertama kolom pertama dari angka 1 menjadi 100
print(b)

[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


##  Matrix pada Numpy

In [33]:
np.ones((2,3))
#ones berarti membuat semua entri pada matriks tersebut menjadi angka 1
#membuat matriks ordo 2x3 dengan entri 1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.zeros((3,2))
#ones berarti membuat semua entri pada matriks tersebut menjadi angka 0
#membuat matriks ordo 3x2 dengan entri 0

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [35]:
np.identity(4)
#identity digunakan untuk matriks identitas
#matriks dengan ordo 4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
np.full((3,2),9)
#membentuk array dengan satu bentuk entri pada seluruh data 
#pada percobaan ini menggunakan angka 9

array([[9, 9],
       [9, 9],
       [9, 9]])

In [37]:
np.random.randint(1,10,size=(3,4))
#random.randint untuk membentuk data array yang berisi angka random namun dengan batas yang telah di tentukan 
#size disini merupakan batas(1,10,size) jadi batas pada percobaan ini adalah 1 sampai 10 
#kemudian (..,..,size = (3,4)) merupakan ordonya jadi matriks ini nanti terdiri dari 3 baris 4 kolom 

array([[6, 1, 7, 2],
       [9, 3, 9, 2],
       [8, 3, 3, 1]])

## Copy pada Numpy

In [38]:
a = np.array([7,22,24,26])
print("data a")
print(a)
print('\n')

b = a.copy()
print("coppy")
print(b)
print('\n')
#copy data menggunakan fungsi copy
#a merupakan data aslinya dan b adalah copy-an 

b[0] = 10
print("diubah")
print(b)
print('\n')
#ubah data b yang merupakan copy-an 
#angka pertama diubah menjadi angka 10
#jadi data b hasilnya akan [10 22 24 26]

print("data a")
print(a)
#data a akan tetap sama seperti awal tidak berubah sama sekali 
#karena yang diubah adalah copy-an nya yaitu data b

[ 7 22 24 26]
[ 7 22 24 26]


coppy
[ 7 22 24 26]


diubah
[10 22 24 26]


[ 7 22 24 26]


## Operasi Matematika pada Numpy

In [39]:
a= np.array([1,2,3,4])
print(a)
b = np.array([7,22,24,26])
print(b)
#masukkan dulu data yang ini di operasikan 

[1 2 3 4]
[ 7 22 24 26]


In [40]:
#tanda + adalah operasi penjumlahan
a+b

array([ 8, 24, 27, 30])

In [41]:
#tanda - adalah operasi pengurangan 
b-b

array([0, 0, 0, 0])

In [42]:
#tanda ** adalah operasi pangkat 
a**3

array([ 1,  8, 27, 64], dtype=int32)

In [43]:
#tanda / adalah operasi pembagian 
b/a

array([ 7. , 11. ,  8. ,  6.5])

In [44]:
#np.tan adalah operasi dari pembentukan nilai tan dari data
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

## Perkalian Matrik pada Numpy

In [53]:
import numpy as np
p = np.array([[1,2,3,4],[5,6,7,8]])
print("matriks p")
print(p)
print('\n')

q = np.array([[7,22,24,26],[2,4,6,8]])
print("matriks q")
print(q)
print('\n')

r = p*q
print("perkalian masing masing entri p dan q")
print (r)
print('\n')
#tanda * akan mengalikan masing masing entri
#r= data p dikali data q 

s = ([[1,2],[3,4],[5,6],[7,8]])
t = np.matmul(p,s)
print("perkalian matriks p dan s")
print(t)
#matmul berfungsi untuk mengalikan dua matriks 
#pada t di minta matriks pxs 

matriks p
[[1 2 3 4]
 [5 6 7 8]]


matriks q
[[ 7 22 24 26]
 [ 2  4  6  8]]


perkalian masing masing entri p dan q
[[  7  44  72 104]
 [ 10  24  42  64]]


perkalian matriks p dan s
[[ 50  60]
 [114 140]]


## min, max dan sum pada Numpy

In [62]:
import numpy as np
c = np.array([[1,2,3], 
              [3,4,5],
              [6,7,8] ])
print("array data c")
print(c)
print('\n')

#"min" digunakan untuk mencari data minimum 
h = np.min(c)
print("nilai minimum")
print(h)
print('\n')

#"min axis=0" digunakan untuk mencari data minimum pada baris data 
#axis=0 menunjukan baris
z = np.min(c, axis=0)
print("nilai minimum baris")
print(z)
print('\n')

#"min axis=1" digunakan untuk mencari data minimum pada kolom data 
#axis=1 menunjukan kolom
f = np.min(c, axis=1)
print("nilai minimum kolom")
print(f)
print('\n')

#"max" digunakan untuk mencari data maksimum
g = np.max(c)
print("nilai maksimum")
print(g)
print('\n')

#"max axis=0" digunakan untuk mencari data maksimum pada baris data 
#axis=0 menunjukan baris
i = np.max(c, axis=0)
print("nilai maksimum baris")
print(i)
print('\n')

#"max axis=1" digunakan untuk mencari data maksimum pada kolom data 
#axis=1 menunjukan kolom
j = np.max(c, axis=1)
print("nilai maksimum kolom")
print(j)
print('\n')

#"sum" digunakan untuk menghitung jumlah seluruh data
k = np.sum(c)
print("jumlah seluruh data")
print(k)
print('\n')

#"sum axis=0" digunakan untuk menghitung jumlah data pada baris 
#axis=0 menunjukan baris
l = np.sum(c, axis=0)
print("jumlah data baris")
print(l)
print('\n')

#"sum axis=1" digunakan untuk menghitung jumlah data pada kolom  
#axis=1 menunjukan kolom
m = np.sum(c, axis=1)
print("jumlah data kolom")
print(m)

array data c
[[1 2 3]
 [3 4 5]
 [6 7 8]]


nilai minimum
1


nilai minimum baris
[1 2 3]


nilai minimum kolom
[1 3 6]


nilai maksimum
8


nilai maksimum baris
[6 7 8]


nilai maksimum kolom
[3 5 8]


jumlah seluruh data
39


jumlah data baris
[10 13 16]


jumlah data kolom
[ 6 12 21]
